use_frameworks!

platform :ios, '8.0'

target 'BevaFLAnimatedImageSDWebCache_Example' do
  pod 'BevaFLAnimatedImageSDWebCache', :path => '../'

  target 'BevaFLAnimatedImageSDWebCache_Tests' do
    inherit! :search_paths

    
  end
end
